In [18]:
import pandas as pd

In [19]:
df_customers = pd.read_csv("./churn_customers.csv")
df_customers.head()

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [20]:
df_customers = pd.read_csv("./churn_customers.csv")
df_customers.tail()

      customerID  gender  SeniorCitizen Partner Dependents
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

In [21]:
df_customers = pd.read_csv("./churn_customers.csv")
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   str
 1   gender         7043 non-null   str
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   str
 4   Dependents     7043 non-null   str
dtypes: int64(1), str(4)
memory usage: 275.2 KB

In [22]:
df_contracts = pd.read_csv("./churn_contracts.csv")
df_contracts.head()

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [23]:
df_contracts = pd.read_csv("./churn_contracts.csv")
df_contracts.tail()

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,24,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [24]:
df_contracts = pd.read_csv("./churn_contracts.csv")
df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7043 non-null   str
 7   Churn             7043 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 440.3 KB

In [25]:
df_services = pd.read_csv("./churn_services.csv")
df_services.head()

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,7590-VHVEG,No,No phone service,DSL,No,Yes,No,No,No,No
1,5575-GNVDE,Yes,No,DSL,Yes,No,Yes,No,No,No
2,3668-QPYBK,Yes,No,DSL,Yes,Yes,No,No,No,No
3,7795-CFOCW,No,No phone service,DSL,Yes,No,Yes,Yes,No,No
4,9237-HQITU,Yes,No,Fiber optic,No,No,No,No,No,No

In [26]:
df_services = pd.read_csv("./churn_services.csv")
df_services.tail()

,customerID,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
7038,6840-RESVB,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes
7039,2234-XADUH,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes
7040,4801-JZAZL,No,No phone service,DSL,Yes,No,No,No,No,No
7041,8361-LTMKD,Yes,Yes,Fiber optic,No,No,No,No,No,No
7042,3186-AJIEK,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes

In [27]:
df_services = pd.read_csv("./churn_services.csv")
df_services.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   PhoneService      7043 non-null   str
 2   MultipleLines     7043 non-null   str
 3   InternetService   7043 non-null   str
 4   OnlineSecurity    7043 non-null   str
 5   OnlineBackup      7043 non-null   str
 6   DeviceProtection  7043 non-null   str
 7   TechSupport       7043 non-null   str
 8   StreamingTV       7043 non-null   str
 9   StreamingMovies   7043 non-null   str
dtypes: str(10)
memory usage: 550.4 KB

#### Transformação de dados

In [ ]:
# Transformar coluna TotalCharges para float - Abordagem 1: astype()
df_contracts.TotalCharges = df_contracts.TotalCharges.astype(float)
# ValueError: could not convert string to float: ' ', ele não consegue converter os valores vazios para float 
df_contracts.info()

In [ ]:
# Transformar coluna TotalCharges para float - Abordagem 2: pd.to_numeric()
df_contracts.TotalCharges = pd.to_numeric(df_contracts.TotalCharges)
# ValueError: Unable to parse string " " at position 488, ele não consegue converter os valores vazios para float
df_contracts.info()

In [32]:
# Transformar coluna TotalCharges para float - Abordagem 2: pd.to_numeric() com argumento errors='coerce' para converter os valores vazios para NaN
df_contracts.TotalCharges = pd.to_numeric(df_contracts.TotalCharges, errors='coerce')
df_contracts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   tenure            7043 non-null   int64
 2   Contract          7043 non-null   str
 3   PaperlessBilling  7043 non-null   str
 4   PaymentMethod     7043 non-null   str
 5   MonthlyCharges    7043 non-null   float64
 6   TotalCharges      7032 non-null   float64
 7   Churn             7043 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 440.3 KB

In [34]:
# Após a transformação da coluna TotalCharges para float, podemos verificar a quantidade de valores ausentes (NaN) na coluna TotalCharges, que correspondem aos valores vazios 
# que não puderam ser convertidos para float.
df_contracts.TotalCharges.isna().sum()

np.int64(11)